import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

enum player {
  x = "X",
  o = "O",
  empty = "empty",
}

const Home: NextPage = () => {
  const [board, setBoard] = useState<player[][]>([
    [player.empty, player.empty, player.empty],
    [player.empty, player.empty, player.empty],
    [player.empty, player.empty, player.empty],
  ]);

  const renderCell = (cell: player) => {
    if (cell === player.empty) {
      return "";
    }

    return cell;
  };

  const renderBoard = () => {
    return (
      <table>
        {board.map((line) => {
          return (
            <tr>
              {line.map((cell) => (
                <td>{renderCell(cell)}</td>
              ))}
            </tr>
          );
        })}
      </table>
    );
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {renderBoard()}
        tiktaktoe
      </main>
    </div>
  );
};

export default Home;
